# Generated by Django 2.0 on 2017-12-26 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('lugar', models.CharField(max_length=200)),
                ('jugadores', models.TextField()),
                ('chat', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador', models.CharField(max_length=15)),
                ('score', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carioca_game_telegram.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounds', models.CharField(choices=[('2T', '2 Trios'), ('1T1E', '1 Trio y 1 Escala'), ('2E', '2 Escalas'), ('3T', '3 Trios'), ('2T1E', '2 Trios y 1 Escala'), ('1T2E', '1 Trio y 2 Escalas'), ('4T', '4 Trios'), ('3E', '3 Estacalas')], max_length=4)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carioca_game_telegram.Game')),
            ],
        ),
        migrations.CreateModel(
            name='RoundResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador', models.CharField(max_length=15)),
                ('score', models.IntegerField()),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carioca_game_telegram.Round')),
            ],
        ),
    ]
