# Generated by Django 2.0 on 2017-12-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carioca_game_telegram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
