# Generated by Django 2.0 on 2017-12-26 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carioca_game_telegram', '0002_game_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
