# Generated by Django 2.0 on 2017-12-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carioca_game_telegram', '0003_round_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='start',
            field=models.BooleanField(default=False),
        ),
    ]
